snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(digit float)"
return_type = "float"
file = "app.zip"
name = "multiplication_udf"
handler = "app.main"
execute_as_caller = true

[dev]
database = "HOL_DB"
schema = "ANALYTICS"
warehouse = "HOL_WH"
role = "HOL_ROLE"
overwrite = true
